#!/bin/bash
# Interactive generator for ./.env (macOS defaults).
# The .env file holds every secret and parameter used by the *-est-enroll*.sh
# scripts. It is git-ignored and written with mode 600.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env}"

# --- Platform defaults (macOS / Homebrew) ------------------------------------
BREW_PREFIX="$(brew --prefix 2>/dev/null || echo /usr/local)"
if [[ -f "$BREW_PREFIX/lib/libykcs11.dylib" ]]; then
  DEFAULT_PKCS11_LIB="$BREW_PREFIX/lib/libykcs11.dylib"
else
  DEFAULT_PKCS11_LIB="/usr/local/lib/libykcs11.dylib"   # Yubico PIV Tool installer
fi
DEFAULT_PKCS11_ENGINE="$(brew --prefix libp11 2>/dev/null || echo "$BREW_PREFIX/opt/libp11")/lib/engines-3/pkcs11.dylib"
DEFAULT_EST_BASE_URL="https://one.ch.digicert.com/.well-known/est"
DEFAULT_SLOT="9a"

# --- Helpers -----------------------------------------------------------------
ask() {            # ask "Prompt" ["default"]  -> value, default when input is empty
  local prompt="$1" default="${2:-}" value
  [[ -n "$default" ]] && prompt="$prompt [$default]"
  read -rp "$prompt: " value
  printf '%s' "${value:-$default}"
}
ask_required() {   # ask_required "Prompt"  -> non-empty value
  local value=""
  while [[ -z "$value" ]]; do read -rp "$1: " value; done
  printf '%s' "$value"
}
ask_secret() {     # ask_secret "Prompt"  -> non-empty value, input hidden
  local value=""
  while [[ -z "$value" ]]; do read -rsp "$1: " value; echo >&2; done
  printf '%s' "$value"
}
esc() {            # escape single quotes so the value is safe inside '...'
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
}

# --- Prompt ------------------------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
  read -rp "$ENV_FILE already exists. Overwrite? [y/N] " answer
  [[ "$answer" =~ ^[Yy]$ ]] || { echo "Aborted, existing file kept."; exit 0; }
fi

echo "Creating $ENV_FILE - press Enter to accept a default shown in [brackets]."
echo
echo "== DigiCert ONE / TLM EST =="
EST_BASE_URL=$(ask "EST base URL" "$DEFAULT_EST_BASE_URL")
EST_PROFILE_ID=$(ask_required "EST profile ID for *-est-enroll.sh (TLM-<uuid>)")
EST_PROFILE_ID_MSCA=$(ask "EST profile ID for *-est-enroll-msca.sh (empty if unused)")
ENROLL_CODE=$(ask_secret "Enrollment code (hidden)")
echo
echo "== Certificate subject =="
CN=$(ask_required "Common name (CN)")
EMAIL=$(ask "Email for the SAN, msca variant only (empty if unused)")
echo
echo "== YubiKey PIV (factory defaults apply right after 'ykman piv reset') =="
SLOT=$(ask "PIV slot" "$DEFAULT_SLOT")
PIN=$(ask_secret "PIV PIN (hidden)")
MGMT_KEY=$(ask_secret "PIV management key, 48 hex chars (hidden)")
echo
echo "== PKCS#11 =="
PKCS11_LIB=$(ask "YubiKey PKCS#11 module (libykcs11)" "$DEFAULT_PKCS11_LIB")
PKCS11_ENGINE=$(ask "OpenSSL pkcs11 engine (libp11)" "$DEFAULT_PKCS11_ENGINE")

# --- Write -------------------------------------------------------------------
umask 077
cat > "$ENV_FILE" << ENV
# Generated by config-mac.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Contains secrets - never commit this file (see .gitignore).

# DigiCert ONE / TLM EST endpoint
EST_BASE_URL='$(esc "$EST_BASE_URL")'
# Profile used by *-est-enroll.sh
EST_PROFILE_ID='$(esc "$EST_PROFILE_ID")'
# Profile used by *-est-enroll-msca.sh
EST_PROFILE_ID_MSCA='$(esc "$EST_PROFILE_ID_MSCA")'
ENROLL_CODE='$(esc "$ENROLL_CODE")'

# Certificate subject (EMAIL becomes the SAN in the msca variant only)
CN='$(esc "$CN")'
EMAIL='$(esc "$EMAIL")'

# YubiKey PIV
SLOT='$(esc "$SLOT")'
PIN='$(esc "$PIN")'
MGMT_KEY='$(esc "$MGMT_KEY")'

# PKCS#11 module and OpenSSL engine
PKCS11_LIB='$(esc "$PKCS11_LIB")'
PKCS11_ENGINE='$(esc "$PKCS11_ENGINE")'
ENV
chmod 600 "$ENV_FILE"

echo
echo "Wrote $ENV_FILE (mode 600). Next: ./mac-est-enroll.sh or ./mac-est-enroll-msca.sh"
